### ISSUE TITLE
AspNetCore Module fails to start

### ISSUE THREAD

**Issue by flagbug** [projectkudu/kudu#2014]
I'm creating this issue based on the following Twitter discussion: https://twitter.com/flagbug/status/733313828889481217

I've deployed my Asp.Net Core RC2 app to Azure App Services via Git deploy, and the deploy work fine, but the AspNetCore module doesn't seem to be able to start:

![2016-05-19 17 10 01 application events - microsoft azure - google chrome](https://cloud.githubusercontent.com/assets/964691/15399435/e1f07d68-1de7-11e6-8538-0790748324fb.png)

I'll try creating a sample project to reproduce this issue, but this will take some time, maybe someone else has an idea what's happening in the meantime

**Comment by davidebbo** [comment]
Can you share your web app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by flagbug** [comment]
Sure, I've just created a fresh deployment at http://tiny-tutors-alexandria-aspnetrc2test.azurewebsites.net/ where I'm also seeing this issue

**Comment by flagbug** [comment]
@davidebbo Sure, I've just created a fresh deployment at http://tiny-tutors-alexandria-aspnetrc2test.azurewebsites.net/ where I'm also seeing this issue

**Comment by davidebbo** [comment]
Interesting. So in your case, you end up with a `.exe` in wwwroot, and web.config pointing to it:

    <aspNetCore processPath=".\Alexandria.exe" arguments="" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />

While with my test app (https://github.com/davidebbo-test/AspNetCoreRC2VS), I end up with no `.exe`, and config instead uses dotnet.exe against an assembly:

    <aspNetCore processPath="dotnet" arguments=".\AspNetCoreRC2.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />

The whole RC2 model is still new to me, so I'll need those guys to help me understand the difference. @davidfowl when do we end up with one model vs the other?

**Comment by davidfowl** [comment]
@troydai we need a standalone test case. 
/cc @moozyk for ideas

**Comment by flagbug** [comment]
@davidebbo This may be because I'm creating a standalone Asp.Net Core application, so I don't have to install .NET Core on the target machine, and instead specified the [Runtime Identifiers](http://dotnet.github.io/docs/core-concepts/rid-catalog.html)

Maybe Kudu doesn't work with standalone apps yet?

**Comment by davidfowl** [comment]
@flagbug is your repository public? Are you setting the urls manually or using the default?

**Comment by flagbug** [comment]
@davidfowl Nope, sorry, it's private :/ Which URLs are you talking about exactly?

**Comment by davidfowl** [comment]
What does your startup.cs look like

**Comment by flagbug** [comment]
@davidfowl https://gist.github.com/flagbug/b59d68c95a4e2f4cbd350590f6c283eb

**Comment by davidfowl** [comment]
Ah need Program.cs not Startup.cs 😄

**Comment by davidfowl** [comment]
Hmm, that looks fine.

**Comment by troydai** [comment]
Standalone case here: https://github.com/troydai/KuduSample05/blob/master/src/SampleApp05/project.json

Yes?

**Comment by davidebbo** [comment]
But we established yesterday that the samples runs fine in Azure Web Apps (after we fixed the bitness). So there must be some difference.

**Comment by flagbug** [comment]
Aha! `rocess '11452' started successfully and is listening on port '22716'.`

Seems like it works if I remove the standalone feature. Still getting a `500 Internal Server Error. An error occurred while starting the application.`, but this seems to be in the application now!

**Comment by flagbug** [comment]
These were the runtimes I was specifying btw:

```
"runtimes": {
    "win81-x64": { },
    "win8-x86": { }
  },
```

**Comment by troydai** [comment]
@flagbug can you try add `win7-x86` to the runtime id list?

**Comment by flagbug** [comment]
@troydai I just noticed that my App Service is set as 64-bit, should I still use `win7-x86`, or should I rather use `win7-x64`?

**Comment by troydai** [comment]
@davidebbo can correct me if I'm wrong. But my understanding is that the architecture of runtime should match your AppServices's architecture, @flagbug.

**Comment by davidebbo** [comment]
Wouldn't it cause a build error though? In your sample, when you had just `"win7-x64"`, build was failing. When we added `"win7-x86"`, it built and ran. But for @flagbug everything builds. Just blows up at runtime.

Still worth a try to add those runtimes in project.json. @flagbug give it a shot!

**Comment by flagbug** [comment]
@troydai Well, that's a bit hard to know with Azure App Services, I have no idea on which OS Version my App is running on, I only know the bitness :smile:

**Comment by davidebbo** [comment]
It's Server 2012 (*not* R2), which I think maps to Win7.

**Comment by moozzyk** [comment]
If the process starts and you get 500 then I would recommend turning on logging. If you use web deploy/publish-iis remove the `stdoutLogFile` attribute or set the value to `\\?\%home%\LogFiles` and set stdoutLogEnabled to `true`. You should see log file which should tell you what happened. 
I have not had a chance to try a portable app (i.e. dll) because dotnet runtime was not installed until yesterday. Standalone (.exe) worked when I tried it last week.

**Comment by davidebbo** [comment]
@flagbug I took the liberty of changing that in your test site:

    <aspNetCore processPath="dotnet" arguments=".\Alexandria.dll" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles" forwardWindowsAuthToken="false" />

But I'm not seeing any interesting logs generated after hitting the site.

**Comment by snobu** [comment]
Windows Server 2012 maps to Windows **8**

https://msdn.microsoft.com/en-us/library/windows/desktop/ms724832(v=vs.85).aspx

**Comment by davidebbo** [comment]
@snobu thanks! Well, so it may not be the root of the issue after all. And since logging is not working, it's hard to diagnose :(

**Comment by hoetz** [comment]
FWIW I redeployed my RC2 site today and now it fails as well.
It ran fine the last couple of days, only css changes and it runs fine locally.
I created a completely new site (the old still had RC1 stuff in it) deployed from github again and still getting "not allowed to list contents" error.
Feel free to look at my site https://3dscom.azurewebsites.net
github source: https://github.com/hoetz/3dshootercom/tree/master/src/Web

**Comment by davidebbo** [comment]
@hoetz please see [Test your ASP.NET Core repo locally](https://github.com/projectkudu/kudu/wiki/Test-your-ASP.NET-Core-repo-locally).

Closing this issue for now as I don't think there is a Kudu issue here. If someone still has an issue after successfully going through the steps locally, we can re-open (or maybe start clean issue).
